### ISSUE TITLE
User Input 

### ISSUE THREAD

**Issue by Joao17Duarte** [Joao17Duarte/capstone-project#13]
The *user* can insert his name in a box
to *create* a group of people 
to *match* the movies that were picked.

## Description
![UserStory 3](https://user-images.githubusercontent.com/66563297/110694192-9bba3680-81e8-11eb-8b36-10f8f2588a6a.png)

## Acceptance criteria
- [ ] one text input to insert the name of player
- [ ] one button to go pick movie

## Tasks
- [ ] create feature branch
- [ ] label and input text
- [ ] create button with text "Pick your Movie"
- [ ] create storybook for this component
