### ISSUE TITLE
Routers

### ISSUE THREAD

**Issue by Joao17Duarte** [Joao17Duarte/capstone-project#15]
The *User* can navigate through the pages without living the main page

##Description

![UserStory 4](https://user-images.githubusercontent.com/66563297/110699055-bf807b00-81ee-11eb-97a9-44c153e97056.png)

## Acceptance criteria

- [x] click in button and redirect to next component

## Tasks

- [x] create a feature branch
- [x] import react-router-dom
- [x] use route, switch and links (when necessary)
