### ISSUE TITLE
Movie List

### ISSUE THREAD

**Issue by Joao17Duarte** [Joao17Duarte/capstone-project#3]
The User will **see a Movie List** 

## Description 
#
![UserStory 1](https://user-images.githubusercontent.com/66563297/110128019-9d3dc600-7dc6-11eb-8bc6-8996430d702a.png)

## Acceptance criteria

- [x] the card got one name of a Movie

## Tasks

- [x] Create a Feature Branch
- [x] add json file with 'n' movies
- [x]  Create a `<h1>` for the title list
- [x] Create a Card
     - [x] Create a Span for the Movie title
     - [x] Add Styles to the Card
     - [x]  Use a fake poster image for the Movie
